import type { RefObject } from "react";
import "./PaginatedEditor.css";
import RichFormattingToolbar from "./RichFormattingToolbar";

const PAGE_CHARACTER_LIMIT = 1800;
type PaginatedEditorProps = { value: string; textareaRef: RefObject<HTMLTextAreaElement | null>; onChange: (value: string) => void; onKeyDown?: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void };
function paginate(value: string) { if (!value) return [""]; const paragraphs = value.split(/\n\n+/); const pages: string[] = []; let page = ""; paragraphs.forEach((paragraph) => { const next = page ? `${page}\n\n${paragraph}` : paragraph; if (next.length > PAGE_CHARACTER_LIMIT && page) { pages.push(page); page = paragraph; } else if (paragraph.length > PAGE_CHARACTER_LIMIT) { for (let index = 0; index < paragraph.length; index += PAGE_CHARACTER_LIMIT) { if (page) pages.push(page); page = paragraph.slice(index, index + PAGE_CHARACTER_LIMIT); } } else page = next; }); if (page || !pages.length) pages.push(page); return pages; }

export default function PaginatedEditor({ value, textareaRef, onChange, onKeyDown }: PaginatedEditorProps) {
  const pages = paginate(value);
  return <div className="page-editor-shell px-1 pb-8 sm:px-6"><div className="mx-auto mb-4 w-full max-w-[794px] rounded-t-lg bg-[#fffdf9]"><RichFormattingToolbar /></div><div className="mx-auto w-full max-w-[794px] space-y-6">{pages.map((page, index) => <article key={index} className="a4-page relative mx-auto min-h-[920px] w-full max-w-[794px] bg-[#fffdf9] px-8 py-14 shadow-[0_5px_18px_rgba(66,43,28,.07)] sm:min-h-[1123px] sm:px-[88px] sm:py-[92px]"><textarea ref={index === 0 ? textareaRef : undefined} value={page} onChange={(event) => { const nextPages = [...pages]; nextPages[index] = event.target.value; onChange(nextPages.join("\n\n")); }} onKeyDown={index === 0 ? onKeyDown : undefined} placeholder={index === 0 ? "Begin with a thought…" : "Continue writing…"} className="editor-textarea block min-h-[820px] w-full resize-none overflow-hidden border-0 bg-transparent p-0 font-['Instrument_Serif',Georgia,serif] text-[1.3rem] leading-[1.82] tracking-[-0.008em] text-[#352b25] outline-none placeholder:text-[#b8aca1] sm:min-h-[939px] sm:text-[1.48rem]" aria-label={`Writing page ${index + 1}`} /><span className="absolute bottom-7 left-0 w-full text-center text-xs tabular-nums text-[#b9aaa0] sm:bottom-10">{index + 1}</span></article>)}</div></div>;
}
