import { Bold, Italic, Underline, Heading2, List, ListChecks, Quote } from "lucide-react";
import type { RefObject } from "react";

type Props = { targetRef: RefObject<HTMLElement | null> };

export default function RichFormattingToolbar({ targetRef }: Props) {
  const target = () => targetRef.current;
  const command = (name: string, value?: string) => { const editor = target(); if (editor instanceof HTMLTextAreaElement) { if (name === "fontName") editor.style.fontFamily = value ?? ""; if (name === "fontSize") editor.style.fontSize = ({ "2": "1.1rem", "3": "1.3rem", "4": "1.6rem", "5": "1.9rem" } as Record<string, string>)[value ?? ""] ?? ""; return; } if (!(editor instanceof HTMLElement)) return; editor.focus(); globalThis.document.execCommand(name, false, value); };
  const wrapTextarea = (prefix: string, suffix = "") => { const editor = target(); if (!(editor instanceof HTMLTextAreaElement)) return; const start = editor.selectionStart; const end = editor.selectionEnd; const selected = editor.value.slice(start, end) || "text"; editor.setRangeText(`${prefix}${selected}${suffix}`, start, end, "select"); editor.dispatchEvent(new Event("input", { bubbles: true })); editor.focus(); };
  const apply = (kind: "bold" | "italic" | "underline") => { const editor = target(); if (editor instanceof HTMLElement && editor.isContentEditable) command(kind); else wrapTextarea(kind === "bold" ? "**" : kind === "italic" ? "*" : "__", kind === "bold" ? "**" : kind === "italic" ? "*" : "__"); };
  const line = (prefix: string) => { const editor = target(); if (editor instanceof HTMLElement && editor.isContentEditable) { if (prefix === "heading") command("formatBlock", "<h2>"); else if (prefix === "quote") command("formatBlock", "<blockquote>"); else command("insertUnorderedList"); } else if (editor instanceof HTMLTextAreaElement) { const start = editor.value.lastIndexOf("\n", editor.selectionStart - 1) + 1; editor.setRangeText(prefix === "heading" ? "## " : prefix === "quote" ? "> " : prefix === "check" ? "- [ ] " : "- ", start, start, "end"); editor.dispatchEvent(new Event("input", { bubbles: true })); editor.focus(); } };
  const buttons = [["Bold", <Bold size={15} />, () => apply("bold")], ["Italic", <Italic size={15} />, () => apply("italic")], ["Underline", <Underline size={15} />, () => apply("underline")], ["Heading", <Heading2 size={15} />, () => line("heading")], ["Bulleted list", <List size={15} />, () => line("list")], ["Checklist", <ListChecks size={15} />, () => line("check")], ["Quote", <Quote size={15} />, () => line("quote")]] as const;
  return <div className="flex flex-wrap items-center gap-0.5 border-b border-[#ece2d8] px-5 py-2 sm:px-8" aria-label="Formatting toolbar">{buttons.map(([label, icon, action]) => <button key={label} type="button" title={label} aria-label={label} onMouseDown={(event) => event.preventDefault()} onClick={action} className="grid h-8 w-8 place-items-center rounded-md text-[#806f63] transition hover:bg-[#f7eee6] hover:text-[#4f3c31]">{icon}</button>)}<span className="mx-1 h-5 w-px bg-[#e5d9cf]" /><select aria-label="Font family" title="Font family" defaultValue="" onChange={(event) => command("fontName", event.target.value)} className="h-8 rounded-md bg-transparent px-1 text-xs text-[#75665c] outline-none hover:bg-[#f7eee6]"><option value="">Font</option><option value="Georgia">Serif</option><option value="Inter">Sans</option><option value="Courier New">Mono</option></select><select aria-label="Font size" title="Font size" defaultValue="" onChange={(event) => command("fontSize", event.target.value)} className="h-8 rounded-md bg-transparent px-1 text-xs text-[#75665c] outline-none hover:bg-[#f7eee6]"><option value="">Size</option><option value="2">Small</option><option value="3">Normal</option><option value="4">Large</option><option value="5">XL</option></select></div>;
}
