import type { RefObject } from "react";
import { Check, Maximize2, Minimize2, Star, X } from "lucide-react";
import EditorStatus from "./EditorStatus";
import WriteToolbar from "./WriteToolbar";
import PaginatedEditor from "./PaginatedEditor";

type WriteScreenProps = {
  text: string; title: string; spaceLabel: string; statusValue: "draft" | "in-progress" | "finished" | "archived"; favorite: boolean; focusMode: boolean; textareaRef: RefObject<HTMLTextAreaElement | null>; wordCount: number; charCount: number; readingMinutes: number; loading: boolean; suggestion: string; status: string; autoHelp: boolean;
  onTextChange: (value: string) => void; onKeyDown: (event: React.KeyboardEvent<HTMLTextAreaElement>) => void; onTitleChange: (title: string) => void; onStatusChange: (status: "draft" | "in-progress" | "finished" | "archived") => void; onToggleFavorite: () => void; onToggleFocus: () => void; onImprove: () => void; onSave: () => void; onSuggestionsChange: (enabled: boolean) => void; onDismissSuggestion: () => void; onUseSuggestion: () => void; onExportPDF: () => void; onExportDOCX: () => void; onExportTXT: () => void;
};

export default function WriteScreen({ text, title, spaceLabel, statusValue, favorite, focusMode, textareaRef, wordCount, charCount, readingMinutes, loading, suggestion, status, autoHelp, onTextChange, onKeyDown, onTitleChange, onStatusChange, onToggleFavorite, onToggleFocus, onImprove, onSave, onSuggestionsChange, onDismissSuggestion, onUseSuggestion, onExportPDF, onExportDOCX, onExportTXT }: WriteScreenProps) {
  return <main className="mx-auto w-full max-w-[1100px] px-6 pb-20 pt-9 sm:px-10 sm:pt-14">
    <header className="mb-7 flex items-start gap-3 sm:mb-9"><div className="min-w-0 flex-1"><input value={title} onChange={(event) => onTitleChange(event.target.value)} placeholder="Untitled note" className="w-full bg-transparent font-['Instrument_Serif',Georgia,serif] text-3xl tracking-[-.035em] text-[#44362e] outline-none placeholder:text-[#b7a99e] sm:text-4xl" aria-label="Document title" /><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-[#95857a]"><span>{spaceLabel}</span><span className="text-[#c9b9ad]">•</span><select value={statusValue} onChange={(event) => onStatusChange(event.target.value as WriteScreenProps["statusValue"])} className="cursor-pointer bg-transparent text-xs text-[#806f63] outline-none"><option value="draft">Draft</option><option value="in-progress">In Progress</option><option value="finished">Finished</option><option value="archived">Archived</option></select><span className="text-[#c9b9ad]">•</span><span>{status || "Saved locally"}</span></div></div><button onClick={onToggleFavorite} className={`rounded-md p-2 ${favorite ? "text-[#b17345]" : "text-[#b9aaa0] hover:bg-[#f6ece3]"}`} aria-label={favorite ? "Unfavorite document" : "Favorite document"}><Star size={17} fill={favorite ? "currentColor" : "none"} /></button><button onClick={onToggleFocus} className="rounded-md p-2 text-[#9c8d82] hover:bg-[#f6ece3]" aria-label={focusMode ? "Exit focus mode" : "Enter focus mode"}>{focusMode ? <Minimize2 size={17} /> : <Maximize2 size={17} />}</button></header>
    <section className="overflow-hidden rounded-[14px] border border-[#e9dfd5] bg-[#f3ece4] transition-colors duration-150 focus-within:border-[#cdb7a5] focus-within:ring-2 focus-within:ring-[#d8c3b2]/35">
      <PaginatedEditor value={text} textareaRef={textareaRef} onChange={onTextChange} onKeyDown={onKeyDown} />
      {loading && <div className="mx-7 mb-6 border-l-2 border-[#bd927a] bg-[#fcf5ee] px-4 py-3 text-sm text-[#785d4d] sm:mx-14">Refining your writing…</div>}
      {!loading && suggestion && <div className="mx-6 mb-5 rounded-xl border border-[#ead9ca] bg-[#fdf6ef] p-4 sm:mx-10"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#986044]">A possible refinement</p><p className="mt-2 font-['Instrument_Serif',Georgia,serif] text-lg leading-relaxed text-[#54443a]">{suggestion}</p></div><button className="text-[#9a887b] hover:text-[#604d41]" onClick={onDismissSuggestion} aria-label="Dismiss suggestion"><X size={17} /></button></div><button className="mt-3 inline-flex items-center gap-1.5 text-xs font-bold text-[#885139] hover:text-[#633622]" onClick={onUseSuggestion}><Check size={14} />Use this version</button></div>}
      <EditorStatus wordCount={wordCount} charCount={charCount} readingMinutes={readingMinutes} status={status} suggestionsEnabled={autoHelp} onSuggestionsChange={onSuggestionsChange} />
      <WriteToolbar loading={loading} onImprove={onImprove} onSave={onSave} onExportPDF={onExportPDF} onExportDOCX={onExportDOCX} onExportTXT={onExportTXT} />
    </section>
  </main>;
}
